baseURL = "https://www.giuliostarace.com/"
theme = "hugo-bearblog"

title = "Giulio Starace"
author = "Giulio Starace"
languagecode = "en-US"


enableRobotsTXT = true

[permalinks]
  blog = "/posts/:slug/"


[params]
title = "Giulio Starace"
description = "Giulio Starace's personal website"
images = [
  "/images/cover.png",
  "https://gravatar.com/avatar/183d6e8b6fcb762d6cbc1c15dd7423da?s=400",
]
hideMadeWithLine = true


favicon = "https://gravatar.com/avatar/183d6e8b6fcb762d6cbc1c15dd7423da?s=32"  

# render raw html
[markup.goldmark.renderer]
unsafe = true

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true
    simple = true
